### ISSUE TITLE
[Bug] Error at "setting up conditionals"

### ISSUE THREAD

**Issue by 46620** [SteamClientHomebrew/Millennium#58]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When launching `user32` after building it throws an error about pygit2 not being a module, causing millennium to not load and not hook into Steam. A snippet of the log is below, with the debug log provided below
```
...
[12:53:45.781] [millennium__internal] setting up conditionals
Traceback (most recent call last):
  File "/home/mia/.steam/steam/steamui/plugins/__millennium__/backend/main.py", line 23, in <module>
    from ffi.git import Updater
  File "/home/mia/.steam/steam/steamui/plugins/__millennium__/backend/ffi/git.py", line 5, in <module>
    import pygit2, os, json, shutil
  File "/home/mia/.steam/steam/steamui/plugins/__millennium__/.millennium/Lib/site-packages/pygit2/__init__.py", line 32, in <module>
    from ._pygit2 import *
ModuleNotFoundError: No module named 'pygit2._pygit2'
[12:53:45.783] [error] millennium failed to startup [millennium__internal]
...
```
[debug.log](https://github.com/user-attachments/files/16045459/debug.log)

I'm testing Arch Linux.

### Expected Behavior

The error shouldn't appear and should load Millennium

### Steps To Reproduce

1. Build Millennium for Linux on the "dev" branch (main currently does not build as of testing)
2. Run "user32"
3. Read the console log

### Operating System

Linux

**Comment by ShadowMonster99** [comment]
I'm still working on proper linux support. not everything is working as expected. you can `pip install pygit2` to your global python site packages and it should fix this issue. this isn't permanent though as Millennium is eventually going to start enforcing Python 3.11.8

**Comment by 46620** [comment]
Yep that fixed the console error. Hyped for the future when the project runs fully on Linux.
